name: Test an action
on: [push]
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Failed step
        uses: ./action

      - name: Do another thing
        run: echo "This is another step"
      
      - name: Last thing
        run: echo "Last step"
